# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data | Code | Experiments
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a data analyst, experiment designer, and budding programmer. This is my Git$
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Abu_Casey
github_username:  Chris-OKeefe

# Build settings
markdown: kramdown

port: 3000 # change server port to 3000
